apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
data:
  index.html: |
    <html>
      <head>
        <title>Welcome to My Web App</title>
      </head>
      <body>
        <h1>Hello, World!</h1>
        <p>This is served from an Apache server on Kubernetes!</p>
      </body>
    </html>
